#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math, operator, zlib

MSG_SIZE = 1500 #MTU
TIMEOUT = 30 #socket timeout
BUFFERED_DATA = {} #buffer of data we have received
BYTES_ADDED = 0 #how many bytes we have added to output
LAST_ACKED = None #seq num of last packet we acked
TOTAL_MSG_LENGTH = None #how many bytes we need in total, will be sent over from sender

class Receiver:
    def __init__(self):
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.port = self.socket.getsockname()[1]
        self.log("Bound to port %d" % self.port)

        self.remote_host = None
        self.remote_port = None
        
        self.received_nums = [-1]
        self.stored_data = []
        self.ack_num = 2

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.remote_host, self.remote_port))

    def log(self, message):
        sys.stderr.write(message + "\n")
        sys.stderr.flush()


    def run(self):
        while True:
            socks = select.select([self.socket], [], [])[0]
            for conn in socks:
                data, addr = conn.recvfrom(65535)

                # Grab the remote host/port if we don't already have it
                if self.remote_host is None:
                    self.remote_host = addr[0]
                    self.remote_port = addr[1]
                try:
                    msg = json.loads(data.decode('utf-8'))
                except ValueError as e:
                    continue
                else:
                    if (msg["type"] == "done"):
                        self.stored_data = sorted(self.stored_data, key=lambda d: d['seq_num']) 
                        for msg in self.stored_data:
                            print(msg["data"], end='', flush=True)
                        self.send({"type": "done"})
                        break
            
                    if (not "data" in msg):
                        continue

                    if (msg["checksum"] != zlib.adler32(bytes((msg["data"] + str(msg["seq_num"])).encode()))):
                        continue
                    seq_num_rec = msg["seq_num"]
                    if (seq_num_rec not in self.received_nums):
                                self.received_nums.append(seq_num_rec)
                                self.stored_data.append(msg)
                        
                # Always send back an ack
                    self.ack_num = self.ack_num + (self.ack_num / 2)
                    self.send({"type": "ack", "ack_num": self.ack_num, "seq_num": msg["seq_num"], "checksum": (str(msg["seq_num"]) + str(self.ack_num)), "start_time": msg["start_time"] })

        return

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='receive data')
    args = parser.parse_args()
    sender = Receiver()
    sender.run()
